spring:
  application:
    name: gateway-service

  cloud:
    config:
      enabled: true

    discovery:
      enabled: true

    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/registration/**
            - Path=/auth/**
            - Path=/api/client/**
            - Path=/api/email/**
            - Path=/users/**
          filters:
            - StripPrefix=1

        - id: planing-service
          uri: lb://PLANING-SERVICE
          predicates:
            - Path=/planning/**
            - Path=/areas/**
          filters:
            - StripPrefix=1

        - id: mailing-service
          uri: lb://MAILING-SERVICE
          predicates:
            - Path=/api/email/**
          filters:
            - StripPrefix=1

        - id: kpi-service
          uri: lb://KPI-SERVICE
          predicates:
            - Path=/api/kpis/**
            - Path=/api/action-plan/**
          filters:
            - StripPrefix=1

        - id: fivee-s-service
          uri: lb://FIVEE-S-SERVICE
          predicates:
            - Path=/api/audits/**
          filters:
            - StripPrefix=1

server:
  port: 9099

jwt:
  secret: aSv9LkJm2Nq7Xt4Yz6Be8Uh3Wf5Rp9Dc4Vg7Kn2Mj5Nx8Qz3Th6Yw9Bs4Hk7
  expiration: 86400000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
