spring:
  application:
    name: kpi-service
  datasource:
    url: jdbc:postgresql://localhost:5432/bd-kpi
    username: postgres
    password: ghada
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring:
          json:
            add:
              type:
                headers: true
            type:
              mapping: PlanOfActionEvent:com.example.commonevents.PlanOfActionEvent
  cloud:
    config:
      enabled: false
    discovery:
      enabled: true
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
usermanagement:
  service:
    url: https://localhost:9094/users
server:
  port: 9098
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: classpath:keystore.p12
    key-store-password: ghada123
    key-alias: myalias
jwt:
  secret: aSv9LkJm2Nq7Xt4Yz6Be8Uh3Wf5Rp9Dc4Vg7Kn2Mj5Nx8Qz3Th6Yw9Bs4Hk7
  expiration: 86400000
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
