spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bd-authentification
    username: postgres
    password: ghada
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: "aSv9LkJm2Nq7Xt4Yz6Be8Uh3Wf5Rp9Dc4Vg7Kn2Mj5Nx8Qz3Th6Yw9Bs4Hk7"
  expiration: 86400000

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG





